### ISSUE TITLE
Sync device list needs a tablet icon

### ISSUE THREAD

**Issue by garvankeeley** [FirefoxUX/photon-icons#3]
There is only mobile phone icon now https://github.com/FirefoxUX/photon-icons/blob/master/icons/desktop/device-mobile-16.svg
We should also have a tablet icon.
Those are used in sync device lists, and the sync device list message specifies mobile phone and mobile tablet.

**Comment by garvankeeley** [comment]
x-ref for iOS bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1462113

**Comment by garvankeeley** [comment]
@ryanfeeley do you know where this is?

**Comment by bwinton** [comment]
Maybe we should do a diff against the stuff in https://dxr.mozilla.org/mozilla-central/source/browser/themes/shared/icons and see where stuff is missing?

**Comment by garvankeeley** [comment]
For this bug, it is https://dxr.mozilla.org/mozilla-central/source/browser/themes/shared/icons/device-tablet.svg

**Comment by aminalhazwani** [comment]
We have a tablet icon in the `/icons` website, see https://design.firefox.com/icons/viewer/#device%20tablet, let me add it here as well and double check if anything else is missing

**Comment by aminalhazwani** [comment]
Ok, the link that I posted up here returns an empty result. We should do an audit of the Photon icons that are on m-c and import them in this repo as @bwinton recommended.
