### ISSUE TITLE
Can i use or edit or redesign "Photon Icons" (used icons in Firefox) for my commercials purposes ?

### ISSUE THREAD

**Issue by kada8** [FirefoxUX/photon-icons#65]
Hi
Can i use or edit or redesign "Photon Icons" (used icons in Firefox) for my commercials purposes and my business?
this link :https://design.firefox.com/icons

**Comment by bwinton** [comment]
Hmm. That's a good question. I'll check with our legal department, but I suspect they'll say that as long as you follow [the license terms for this repo](https://github.com/FirefoxUX/photon-icons/blob/master/LICENSE), you should be fine.

**Comment by kada8** [comment]
Hi
When can you give a definite answer from legal department?
I want to know can i use or not for my commercials purposes?

**Comment by bwinton** [comment]
That will depend on when legal can get back to me. Since it's Sunday, it seems unlikely that it'll be today.

**Comment by bwinton** [comment]
So, I have an answer.
The content in this repository is available under the Mozilla Public License 2.0.  You are welcome to use it as long as you follow the terms of the license. If you have other legal questions, you should consult your own legal team.
Hope this helps!

**Comment by kada8** [comment]
Hi @bwinton
I needed your answer to use it safely and not worry.
Thank you.
